#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

set -e

readonly PROGNAME=$(basename $0)
readonly PROGDIR=$(readlink -m $(dirname $0))


[ -n "$FOAM_EXT_LIBBIN" ] || {
    echo "Error: FOAM_EXT_LIBBIN not set"
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
}

[ -d "$ATMOSFOAM_TOOLS_SRC" ] || {
    echo "Error: ATMOSFOAM_SRC directory does not exist"
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
}

src/Allwmake $*
echo "\033[1;37m All codes up to date in $PROGDIR/src \033[0m" #white text
applications/Allwmake $*

echo "\033[1;37m All codes up to date in $PROGDIR/applications \033[0m" #white text

echo "\033[1;35m All codes up to date in $PROGDIR \033[0m" #purple text
