#!/bin/bash
set -o errexit
set -o nounset

script=rmInletOutlet

cat <<EOF > $script.sh
set -o errexit
rm_inlet(){
sed -i '/inlet/,/}/d' \$1
}
rm_outlet(){
sed -i '/outlet/,/unknown;/d' \$1
}
change_nboundary(){
sed -i 's/^6\$/4/g' \$1
}

rm_inlet \$1
rm_outlet \$1
change_nboundary \$1
EOF
chmod 744 $script.sh

mv $script.sh $FOAM_USER_APPBIN/$script
echo $script created
